# ---------------
# Server settings
# ---------------

server:
  port: 8444


app:
  client:
    baseUrl: http://localhost:8444

# ---------------
# Core Spring settings
# ---------------
spring:
  datasource:
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/fanyacode
    username: postgres
    password: postgres

#  jpa:
#    show-sql : true
#    hibernate:
#      ddl-auto : create
#
#    properties:
#      hibernate:
#        hbm2dll:
#          create_namespaces : true

# ---------------
# OPA
# ---------------
opa:
  client:
    url: http://localhost:8555/v1/data


# ---------------
# Feign
# ---------------
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

#  flyway:
#    url: jdbc:postgresql://localhost:5432/fanyacode?currentSchema=auth
#    user: postgres
#    password: postgres
#    schemas: auth
